language: cpp
compiler:
  - gcc
  - clang
env:
  - STD=
  - STD=c++98
  - STD=c++03
  - STD=c++11

sudo: required
dist: trusty
git:
  depth: 3

script:
  - make -C test STD=$STD
  - make -C test STD=$STD OPT=3
  - make -C test STD=$STD OPT=fast
