language: cpp
compiler:
  - gcc
  - clang
env:
  - STD=
  - STD=c++98
  - STD=c++11
  - OPT=3
  - OPT=fast
matrix:
  exclude:
    - compiler: gcc
      env: STD=c++11
    - compiler: clang
      env: OPT=fast

sudo: false

script: make -C test STD=$STD OPT=$OPT
